### ISSUE TITLE
Instalar Arduino IDE e compatibilidade com o LinkitOne

### ISSUE THREAD

**Issue by vascobnunes** [vascobnunes/CSWspacepeek#9]

**Comment by framioco** [comment]
Downloaded Arduino 1.6.8 for ARM (https://github.com/NicoHood/Arduino/releases) and Java 8 (http://www.rpiblog.com/2014/03/installing-oracle-jdk-8-on-raspberry-pi.html); Also upgraded the OS since some necessary packages were a bit outdated. Still we have an error trying to execute arduino:
/home/pi/arduino-1.6.8/lib/libastylej.so: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/pi/arduino-1.6.8/lib/libastylej.so)
Cannot load native library /home/pi/arduino-1.6.8/lib/libastylej.so
The program has terminated!

**Comment by framioco** [comment]
Updating OS from debian wheezy to jessie - that will fix this problem and bring more updated packages to the system overall. Hope everything goes fine! Will report here shortly after the upgrade is done.

**Comment by framioco** [comment]
OS upgraded to debian jessie which brings the libstdc++6 version up to date (to the required version by Arduino IDE). The IDE now runs (haven't tried to connect to the Linkit board though).

**Comment by vascobnunes** [comment]
Nice! Thanks @framioco

**Comment by framioco** [comment]
Mediatek LinkIt board installed via Board Manager in the Arduino IDE.
